-- Check exact column names and sample data for Daniel incandela
SELECT 
  id,
  nome,
  cognome,
  codice_fiscale,
  sesso,
  data_nascita,
  luogo_nascita,
  citta_nascita,
  comune_nascita,
  provincia_nascita,
  indirizzo,
  numero_civico,
  cap,
  codice_postale,
  citta,
  citta_residenza,
  comune,
  provincia,
  provincia_residenza,
  numero_patente,
  patente,
  tipo_patente,
  categoria_patente,
  emessa_da,
  rilasciata_da,
  data_rilascio,
  data_rilascio_patente,
  scadenza_patente,
  data_scadenza_patente,
  telefono,
  email,
  pec,
  nazione,
  tipo_cliente,
  created_at,
  updated_at
FROM customers_extended
WHERE nome = 'Daniel' AND cognome = 'incandela'
LIMIT 1;
