-- Migration: Update car_wash_services table to support 32 services with categories
-- Run this in Supabase SQL Editor

-- Step 1: Add new columns if they don't exist
ALTER TABLE car_wash_services ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'urban';
ALTER TABLE car_wash_services ADD COLUMN IF NOT EXISTS main_tab TEXT DEFAULT 'lavaggio';
ALTER TABLE car_wash_services ADD COLUMN IF NOT EXISTS price_unit TEXT;
ALTER TABLE car_wash_services ADD COLUMN IF NOT EXISTS price_options JSONB;

-- Step 2: Delete old services (optional - comment out if you want to keep old data)
DELETE FROM car_wash_services;

-- Step 3: Insert all 32 services

-- ==================== LAVAGGIO - URBAN CLASS (1-7) ====================
INSERT INTO car_wash_services (id, name, name_en, price, duration, description, description_en, features, features_en, display_order, is_active, category, main_tab) VALUES
('urban-interior', 'PRIME INTERIOR CLEAN', 'PRIME INTERIOR CLEAN', 19.90, '30 min', 'Abitacolo pulito, aria migliore, comfort immediato.', 'Clean cabin, better air, immediate comfort.', ARRAY['Aspirazione completa (sedili, moquette, tappetini)', 'Pulizia superfici interne', 'Vetri interni anti-aloni', 'Rifinitura plastiche'], ARRAY['Complete vacuuming (seats, carpet, mats)', 'Interior surfaces cleaning', 'Anti-halo interior glass', 'Plastic finishing'], 1, true, 'urban', 'lavaggio'),
('urban-exterior', 'PRIME EXTERIOR CLEAN', 'PRIME EXTERIOR CLEAN', 14.90, '15 min', 'Auto presentabile, pulita, ordinata.', 'Presentable, clean, tidy car.', ARRAY['Prelavaggio', 'Lavaggio carrozzeria', 'Vetri esterni', 'Cerchi rapidi', 'Asciugatura a mano'], ARRAY['Pre-wash', 'Body wash', 'Exterior glass', 'Quick wheels', 'Hand drying'], 2, true, 'urban', 'lavaggio'),
('urban-full', 'PRIME FULL CLEAN', 'PRIME FULL CLEAN', 24.90, '45 min', 'Pulita dentro e fuori senza "mezze misure".', 'Clean inside and out, no half measures.', ARRAY['Interni + esterni completi', 'Schiuma profumata', 'Cerchi/Passaruota/Vetri', 'Aspirazione profonda', 'Asciugatura e rifinitura'], ARRAY['Complete interior + exterior', 'Scented foam', 'Wheels/Wheel arches/Glass', 'Deep vacuuming', 'Drying and finishing'], 3, true, 'urban', 'lavaggio'),
('urban-full-n2', 'PRIME FULL CLEAN N₂', 'PRIME FULL CLEAN N₂', 34.90, '50 min', 'Aria pulita, odori eliminati alla radice.', 'Clean air, odors eliminated at the root.', ARRAY['Tutto il Full Clean', 'Sanificazione abitacolo all''azoto'], ARRAY['Everything from Full Clean', 'Nitrogen cabin sanitization'], 4, true, 'urban', 'lavaggio'),
('urban-top-shine', 'PRIME TOP SHINE', 'PRIME TOP SHINE', 49, '90 min', 'Più brillantezza, più protezione, più presenza.', 'More shine, more protection, more presence.', ARRAY['Full Clean + trattamento lucidante veloce', 'Rifinitura extra plastiche e bocchette', 'Dettagli più curati', 'Acqua Prime Luxury'], ARRAY['Full Clean + quick polish treatment', 'Extra plastic and vent finishing', 'More detailed care', 'Prime Luxury Water'], 5, true, 'urban', 'lavaggio'),
('urban-vip', 'PRIME VIP EXPERIENCE', 'PRIME VIP EXPERIENCE', 75, '120 min', 'Auto rigenerata, non solo pulita.', 'Regenerated car, not just clean.', ARRAY['Top Shine + decontaminazione carrozzeria', 'Pulizia e igienizzazione sedili pelle', 'Sanificazione all''azoto', 'Sigillante premium', 'Profumo premium + omaggio', 'Acqua Prime Luxury'], ARRAY['Top Shine + body decontamination', 'Leather seat cleaning and sanitization', 'Nitrogen sanitization', 'Premium sealant', 'Premium perfume + gift', 'Prime Luxury Water'], 6, true, 'urban', 'lavaggio'),
('urban-luxury', 'PRIME LUXURY DETAIL', 'PRIME LUXURY DETAIL', 119, '180 min', 'Effetto concessionaria. Punto.', 'Dealership effect. Period.', ARRAY['VIP Experience + igienizzazione totale dettagli', 'Sedili (tessuto o pelle), moquette e tappetini', 'Cielo interno', 'Vano motore con prodotti specifici', 'Profumo premium + Acqua Prime Luxury'], ARRAY['VIP Experience + total detail sanitization', 'Seats (fabric or leather), carpet and mats', 'Headliner', 'Engine bay with specific products', 'Premium perfume + Prime Luxury Water'], 7, true, 'urban', 'lavaggio');

-- ==================== LAVAGGIO - MAXI CLASS (8-14) ====================
INSERT INTO car_wash_services (id, name, name_en, price, duration, description, description_en, features, features_en, display_order, is_active, category, main_tab) VALUES
('maxi-interior', 'PRIME MAXI INTERIOR CLEAN', 'PRIME MAXI INTERIOR CLEAN', 24.90, '35 min', 'Ordine reale, niente zone "saltate".', 'Real order, no "skipped" areas.', ARRAY['Aspirazione completa (volumi grandi)', 'Pulizia superfici', 'Vetri interni', 'Rifinitura plastiche'], ARRAY['Complete vacuuming (large volumes)', 'Surface cleaning', 'Interior glass', 'Plastic finishing'], 8, true, 'maxi', 'lavaggio'),
('maxi-exterior', 'PRIME MAXI EXTERIOR CLEAN', 'PRIME MAXI EXTERIOR CLEAN', 19.90, '20 min', 'Grande auto, grande impatto.', 'Big car, big impact.', ARRAY['Prelavaggio, lavaggio carrozzeria', 'Vetri, cerchi rapidi', 'Asciugatura a mano'], ARRAY['Pre-wash, body wash', 'Glass, quick wheels', 'Hand drying'], 9, true, 'maxi', 'lavaggio'),
('maxi-full', 'PRIME MAXI FULL CLEAN', 'PRIME MAXI FULL CLEAN', 29.90, '55 min', 'Pulizia totale, visibile.', 'Total, visible cleaning.', ARRAY['Interni + esterni completi', 'Schiuma profumata', 'Cerchi/passaruota/vetri', 'Aspirazione e rifinitura'], ARRAY['Complete interior + exterior', 'Scented foam', 'Wheels/wheel arches/glass', 'Vacuuming and finishing'], 10, true, 'maxi', 'lavaggio'),
('maxi-full-n2', 'PRIME MAXI FULL CLEAN N₂', 'PRIME MAXI FULL CLEAN N₂', 39.90, '55 min', 'Igiene profonda per famiglie e viaggi.', 'Deep hygiene for families and travel.', ARRAY['Maxi Full Clean + sanificazione all''azoto'], ARRAY['Maxi Full Clean + nitrogen sanitization'], 11, true, 'maxi', 'lavaggio'),
('maxi-top-shine', 'PRIME TOP SHINE MAXI', 'PRIME TOP SHINE MAXI', 59, '100 min', 'Presenza premium.', 'Premium presence.', ARRAY['Maxi Full Clean + lucidante veloce', 'Rifiniture extra', 'Dettagli curati', 'Acqua Prime Luxury'], ARRAY['Maxi Full Clean + quick polish', 'Extra finishing', 'Detailed care', 'Prime Luxury Water'], 12, true, 'maxi', 'lavaggio'),
('maxi-vip', 'PRIME VIP EXPERIENCE MAXI', 'PRIME VIP EXPERIENCE MAXI', 85, '130 min', '"Come nuova", anche sui grandi volumi.', '"Like new", even on large vehicles.', ARRAY['Top Shine Maxi + decontaminazione', 'Sedili pelle', 'Sanificazione all''azoto', 'Sigillante premium', 'Profumo premium + omaggio', 'Acqua Prime Luxury'], ARRAY['Top Shine Maxi + decontamination', 'Leather seats', 'Nitrogen sanitization', 'Premium sealant', 'Premium perfume + gift', 'Prime Luxury Water'], 13, true, 'maxi', 'lavaggio'),
('maxi-luxury', 'PRIME LUXURY DETAIL MAXI', 'PRIME LUXURY DETAIL MAXI', 179, '240 min', 'Rigenerazione completa.', 'Complete regeneration.', ARRAY['VIP Maxi + igienizzazione totale', 'Sedili (tessuto/pelle)', 'Moquette/tappetini', 'Cielo', 'Vano motore', 'Profumo premium + Acqua Prime Luxury'], ARRAY['VIP Maxi + total sanitization', 'Seats (fabric/leather)', 'Carpet/mats', 'Headliner', 'Engine bay', 'Premium perfume + Prime Luxury Water'], 14, true, 'maxi', 'lavaggio');

-- ==================== LAVAGGIO - EXTRA CARE (15-24) ====================
INSERT INTO car_wash_services (id, name, name_en, price, duration, description, description_en, features, features_en, display_order, is_active, category, main_tab) VALUES
('extra-child', 'PRIME CHILD CARE', 'PRIME CHILD CARE', 14.90, '15 min', 'Igiene e tranquillità.', 'Hygiene and peace of mind.', ARRAY['Pulizia e igienizzazione seggiolino', 'Trattamento macchie'], ARRAY['Child seat cleaning and sanitization', 'Stain treatment'], 15, true, 'extra', 'lavaggio'),
('extra-engine', 'PRIME ENGINE CLEAN', 'PRIME ENGINE CLEAN', 29.90, '30 min', 'Motore pulito e ordinato.', 'Clean and tidy engine.', ARRAY['Pulizia vano motore con prodotti specifici', 'Tecnica safe', 'Rifinitura plastiche'], ARRAY['Engine bay cleaning with specific products', 'Safe technique', 'Plastic finishing'], 16, true, 'extra', 'lavaggio'),
('extra-glass', 'PRIME GLASS CARE', 'PRIME GLASS CARE', 9.90, '10 min', 'Visibilità perfetta.', 'Perfect visibility.', ARRAY['Vetri interni/esterni + anti-aloni'], ARRAY['Interior/exterior glass + anti-halo'], 17, true, 'extra', 'lavaggio'),
('extra-odor', 'PRIME ODOR CONTROL', 'PRIME ODOR CONTROL', 9.90, '5 min', 'Aria pulita.', 'Clean air.', ARRAY['Trattamento neutralizzante + profumazione premium'], ARRAY['Neutralizing treatment + premium fragrance'], 18, true, 'extra', 'lavaggio'),
('extra-pet', 'PRIME PET CLEAN', 'PRIME PET CLEAN', 19.90, '20 min', 'Tessuti liberi dai peli.', 'Fabrics free from pet hair.', ARRAY['Rimozione peli con strumenti dedicati', 'Aspirazione mirata'], ARRAY['Pet hair removal with dedicated tools', 'Targeted vacuuming'], 19, true, 'extra', 'lavaggio'),
('extra-plastic', 'PRIME PLASTIC REFRESH', 'PRIME PLASTIC REFRESH', 14.90, '15 min', 'Plastiche piene e curate.', 'Full and well-maintained plastics.', ARRAY['Pulizia + ravvivante protettivo (no effetto unto)'], ARRAY['Cleaning + protective revitalizer (no greasy effect)'], 20, true, 'extra', 'lavaggio'),
('extra-quick-shine', 'PRIME QUICK SHINE', 'PRIME QUICK SHINE', 14.90, '10 min', 'Più gloss subito.', 'More gloss immediately.', ARRAY['Cera spray protettiva + rifinitura'], ARRAY['Protective spray wax + finishing'], 21, true, 'extra', 'lavaggio'),
('extra-rim', 'PRIME RIM CARE', 'PRIME RIM CARE', 9.90, '10 min', 'Look più "nuovo".', 'More "new" look.', ARRAY['Detergente specifico', 'Spazzolatura fronte cerchio', 'Rifinitura gomme'], ARRAY['Specific detergent', 'Wheel face brushing', 'Tire finishing'], 22, true, 'extra', 'lavaggio', 'per 4 cerchi', NULL),
('extra-seat-clean', 'PRIME SEAT CLEAN', 'PRIME SEAT CLEAN', 9.90, '15 min', 'Sedile davvero pulito.', 'Truly clean seat.', ARRAY['Pretrattamento', 'Pulizia profonda in base al materiale', 'Asciugatura controllata'], ARRAY['Pre-treatment', 'Deep cleaning based on material', 'Controlled drying'], 23, true, 'extra', 'lavaggio', 'a sedile', NULL),
('extra-seat-protect', 'PRIME SEAT PROTECT', 'PRIME SEAT PROTECT', 14.90, '10 min', 'Sedili più protetti nel tempo.', 'Seats more protected over time.', ARRAY['Trattamento protettivo sedili'], ARRAY['Seat protective treatment'], 24, true, 'extra', 'lavaggio', 'a sedile', NULL);

-- ==================== LAVAGGIO - MOTO EXPERIENCE (25) ====================
INSERT INTO car_wash_services (id, name, name_en, price, duration, description, description_en, features, features_en, display_order, is_active, category, main_tab) VALUES
('moto-essential', 'PRIME MOTO ESSENTIAL', 'PRIME MOTO ESSENTIAL', 9.90, '20 min', 'Prelavaggio, lavaggio parti esterne con detergenti safe, pulizia zone accessibili, asciugatura a mano.', 'Pre-wash, exterior wash with safe detergents, accessible areas cleaning, hand drying.', ARRAY['Prelavaggio', 'Lavaggio parti esterne con detergenti safe', 'Pulizia zone accessibili', 'Asciugatura a mano'], ARRAY['Pre-wash', 'Exterior wash with safe detergents', 'Accessible areas cleaning', 'Hand drying'], 25, true, 'moto', 'lavaggio');

-- ==================== LAVAGGIO - MOBILITY EXPERIENCE (26-28) ====================
INSERT INTO car_wash_services (id, name, name_en, price, duration, description, description_en, features, features_en, display_order, is_active, category, main_tab, price_options) VALUES
('extra-courtesy', 'PRIME COURTESY DRIVE', 'PRIME COURTESY DRIVE', 9.90, '-', 'Nessuna attesa, nessuna perdita di tempo.', 'No waiting, no time wasted.', ARRAY['Auto pronta all''uso mentre la tua viene lavata'], ARRAY['Car ready to use while yours is being washed'], 26, true, 'experience', 'lavaggio', '[{"label": "1 ora", "price": 9.90}, {"label": "2 ore", "price": 14.90}, {"label": "3 ore", "price": 19.90}, {"label": "4+ ore", "price": 5.90}]'::jsonb),
('extra-supercar', 'SUPERCAR EXPERIENCE', 'SUPERCAR EXPERIENCE', 89, '-', 'Non è un servizio. È un''esperienza.', 'It''s not a service. It''s an experience.', ARRAY['Guida una delle nostre supercar mentre la tua auto viene trattata'], ARRAY['Drive one of our supercars while your car is being treated'], 27, true, 'experience', 'lavaggio', '[{"label": "1 ora", "price": 89}, {"label": "2 ore", "price": 149}, {"label": "3 ore", "price": 189}, {"label": "4+ ore", "price": 69}]'::jsonb),
('extra-icon', 'PRIME ICON EXPERIENCE', 'PRIME ICON EXPERIENCE', 189, '-', 'L''esperienza definitiva. Lamborghini & Ferrari.', 'The ultimate experience. Lamborghini & Ferrari.', ARRAY['Guidi una Lamborghini o una Ferrari mentre la tua auto viene rigenerata'], ARRAY['Drive a Lamborghini or Ferrari while your car is being regenerated'], 28, true, 'experience', 'lavaggio', '[{"label": "1 ora", "price": 189}, {"label": "2 ore", "price": 289}, {"label": "3 ore", "price": 349}, {"label": "4+ ore", "price": 69}]'::jsonb);

-- ==================== MECCANICA - TECH SERVICE (29-32) ====================
INSERT INTO car_wash_services (id, name, name_en, price, duration, description, description_en, features, features_en, display_order, is_active, category, main_tab) VALUES
('tech-brake', 'PRIME BRAKE SERVICE', 'PRIME BRAKE SERVICE', 29, '30 min', 'Controllo e manutenzione freni.', 'Brake check and maintenance.', ARRAY['Controllo pastiglie', 'Controllo dischi', 'Verifica liquido freni'], ARRAY['Brake pad check', 'Disc check', 'Brake fluid check'], 29, true, 'tech', 'meccanica'),
('tech-battery', 'PRIME BATTERY SWAP', 'PRIME BATTERY SWAP', 19, '15 min', 'Sostituzione batteria rapida.', 'Quick battery replacement.', ARRAY['Rimozione batteria vecchia', 'Installazione batteria nuova', 'Test avviamento'], ARRAY['Old battery removal', 'New battery installation', 'Start test'], 30, true, 'tech', 'meccanica'),
('tech-wiper', 'PRIME WIPER SERVICE', 'PRIME WIPER SERVICE', 9.90, '5 min', 'Visibilità e sicurezza di guida.', 'Visibility and driving safety.', ARRAY['Rimozione spazzole usurate', 'Installazione nuove spazzole', 'Verifica corretta aderenza'], ARRAY['Worn blade removal', 'New blade installation', 'Proper adhesion check'], 31, true, 'tech', 'meccanica', 'anteriore o posteriore'),
('tech-headlight', 'PRIME HEADLIGHT RESTORE', 'PRIME HEADLIGHT RESTORE', 34.90, '30 min', 'Migliora estetica, visibilità e sicurezza.', 'Improves aesthetics, visibility and safety.', ARRAY['Pulizia profonda del faro', 'Lucidatura progressiva', 'Ripristino trasparenza'], ARRAY['Deep headlight cleaning', 'Progressive polishing', 'Transparency restoration'], 32, true, 'tech', 'meccanica', NULL, '[{"label": "1 faro", "price": 34.90}, {"label": "2 fari", "price": 59.90}, {"label": "4 fari", "price": 89.90}]'::jsonb);

-- Verify the data
SELECT id, name, category, main_tab, price, display_order FROM car_wash_services ORDER BY display_order;
