-- Seed 164 articoli inventario (da Inventario_Magazzino_DR7.xlsx)
-- Idempotente: upsert per codice. quantita/giacenza_pct NON sovrascritti su update.
INSERT INTO public.inv_articoli (codice, categoria_codice, nome, quantita, unita, giacenza_pct, note) VALUES
  ('DR7-CAF-001','CAF','Stecche di bicchieri per caffè',13,'stecche',NULL,NULL),
  ('DR7-CAF-002','CAF','Bottiglie Voss marchiate DR7',26,'1 cartone',NULL,NULL),
  ('DR7-CAF-003','CAF','Caffè Lavazza',6000,'Formato 1 kg',NULL,NULL),
  ('DR7-CAF-004','CAF','Caffè Lavazza Decaffeinato',500,'Formato 500 g',NULL,NULL),
  ('DR7-CAF-005','CAF','Caffè Illy in grani',4,'latte',NULL,NULL),
  ('DR7-CAF-006','CAF','Caffè Illy in grani',500,'Formato 500 g',NULL,NULL),
  ('DR7-CAF-007','CAF','Cialde Gimoka verdi',1,'pacco',NULL,NULL),
  ('DR7-CAF-008','CAF','Decalcificante De''Longhi',2,'confezioni',NULL,NULL),
  ('DR7-CAF-009','CAF','Bustine di zucchero',4,'scatole',NULL,NULL),
  ('DR7-CAF-010','CAF','Zucchero Dolciando in bustine',1,'pacco',NULL,NULL),
  ('DR7-CAF-011','CAF','Bacchette in legno per caffè',1,'scatola',NULL,NULL),
  ('DR7-CAF-012','CAF','Bacchette in plastica per caffè',1,'scatola',50,'Confezione iniziata'),
  ('DR7-CAF-013','CAF','Bicchieri di carta effetto marmo e oro',1,'scatola',NULL,NULL),
  ('DR7-CAF-014','CAF','Scatolone bicchieri di plastica bianchi',1,'scatolone',NULL,'15 pacchi'),
  ('DR7-CAF-015','CAF','Scatolone bicchieri di carta DR7 / neri',1,'scatolone',NULL,NULL),
  ('DR7-CAF-016','CAF','Bicchierini dorati',15,'pacchi',NULL,NULL),
  ('DR7-CAF-017','CAF','Bicchierini neri',17,'pacchi',NULL,NULL),
  ('DR7-CAF-018','CAF','Bicchierini colorati',12,'pacchi',NULL,NULL),
  ('DR7-CAF-019','CAF','Biscotti Biscoff',2,'pacchi',NULL,NULL),
  ('DR7-CAF-020','CAF','Acqua Panna',10,'casse',NULL,'24 bottiglie/cassa · tot. 240'),
  ('DR7-CAF-021','CAF','Acqua Venere',8,'cartoni',NULL,'6 bottiglie/cartone · tot. 48'),
  ('DR7-PUL-001','PUL','Sapone liquido',4,'buste',NULL,NULL),
  ('DR7-PUL-002','PUL','Sacchi rifiuti grigi 30 L',12,'pacchi',NULL,NULL),
  ('DR7-PUL-003','PUL','Sacchi rifiuti 110 L',13,'pacchi',NULL,NULL),
  ('DR7-PUL-004','PUL','Ace detergente',7,'flaconi',NULL,NULL),
  ('DR7-PUL-005','PUL','Pet Odor Solution',1,'flacone',NULL,NULL),
  ('DR7-PUL-006','PUL','Wood Floor Care Solution',1,'flacone',NULL,NULL),
  ('DR7-PUL-007','PUL','Multi Surface Floor Cleaner',1,'flacone',NULL,NULL),
  ('DR7-PUL-008','PUL','Carta igienica Total Black',8,'rotoli',NULL,NULL),
  ('DR7-PUL-009','PUL','Rotoloni Scottex',3,'rotoli',NULL,'2 nuovi + 1 iniziato'),
  ('DR7-PUL-010','PUL','Scatole fazzoletti DR7',4,'scatole',NULL,NULL),
  ('DR7-PUL-011','PUL','Fazzolettini neri quadrati',1,'pacco',NULL,NULL),
  ('DR7-PUL-012','PUL','Panni in microfibra neri',1,'pacco',NULL,'Confezione iniziata'),
  ('DR7-PUL-013','PUL','Liquido al talco per diffusori ambiente',1,'boccetta',NULL,NULL),
  ('DR7-PUL-014','PUL','Spruzzino lavavetri',1,'spruzzino',NULL,NULL),
  ('DR7-PUL-015','PUL','Spruzzino con acqua',1,'spruzzino',NULL,NULL),
  ('DR7-PUL-016','PUL','Igienizzante pavimenti alla pesca',1,'tanica',50,NULL),
  ('DR7-PUL-017','PUL','Candeggina',1,'tanica',100,'Nuova'),
  ('DR7-PUL-018','PUL','Amuchina Gel disinfettante mani',1,'tanica',70,NULL),
  ('DR7-PUL-019','PUL','Swiffer / Panno cattura polvere ricaricabile',1,'pezzi',NULL,NULL),
  ('DR7-PUL-020','PUL','Sgrassatore Chanteclair universale (giallo)',1,'spruzzino',NULL,NULL),
  ('DR7-PUL-021','PUL','Sgrassatore Chanteclair con candeggina',1,'spruzzino',NULL,NULL),
  ('DR7-PUL-022','PUL','Igienizzante multiuso',1,'spruzzino',NULL,NULL),
  ('DR7-PUL-023','PUL','Detergente multiuso',1,'spruzzino',NULL,NULL),
  ('DR7-PUL-024','PUL','CIF Spray Attivo Igienizzante con candeggina',1,'spruzzino',NULL,NULL),
  ('DR7-PUL-025','PUL','Deodorante ambienti spray alla vaniglia',0,'bomboletta',NULL,'Ultima confezione quasi terminata - da riordinare'),
  ('DR7-DPI-001','DPI','Guanti monouso',10,'scatole',NULL,'≈ 1.500 guanti'),
  ('DR7-DPI-002','DPI','Coprisedili monouso bianchi',1,'rotolo',NULL,NULL),
  ('DR7-DPI-003','DPI','Pellicola estensibile trasparente',3,'rotoli',NULL,NULL),
  ('DR7-DPI-004','DPI','Pellicola estensibile nera',1,'rotolo',NULL,NULL),
  ('DR7-DPI-005','DPI','Calzari monouso blu per scarpe',1,'pacco',NULL,'Pacco iniziato'),
  ('DR7-DPI-006','DPI','Cuffiette per walkie-talkie',3,'pezzi',NULL,NULL),
  ('DR7-UFF-001','UFF','Carta A4',4,'risme',NULL,NULL),
  ('DR7-UFF-002','UFF','Agenda marchiata DR7',1,'pezzi',NULL,NULL),
  ('DR7-MKT-001','MKT','Tappeti neri da esterno',10,'pezzi',NULL,NULL),
  ('DR7-MKT-002','MKT','Pannelli decorativi con fogliame artificiale',3,'pezzi',NULL,NULL),
  ('DR7-MKT-003','MKT','Cartellini "Reserved"',1,'pacchetto',NULL,'3 cartellini'),
  ('DR7-MKT-004','MKT','Profumatori auto',1,'scatoletta',NULL,'19 profumatori'),
  ('DR7-SNK-001','SNK','Golia Bianca',1,'pacco',NULL,NULL),
  ('DR7-SNK-002','SNK','Vigorsol Menta',1,'pacco',NULL,NULL),
  ('DR7-LUB-001','LUB','Antigelo puro rosso',1,'flacone',NULL,NULL),
  ('DR7-LUB-002','LUB','Protettivo radiatori concentrato rosso',4,'flaconi',NULL,NULL),
  ('DR7-LUB-003','LUB','Castrol Edge Professional 0W-20',6,'flaconi',NULL,NULL),
  ('DR7-LUB-004','LUB','Selenia ECO2 Mopar',7,'flaconi',NULL,NULL),
  ('DR7-LUB-005','LUB','Bardahl 5W-30 R17',10,'2 taniche da 5 L',NULL,NULL),
  ('DR7-LUB-006','LUB','Madoil Ultra Synth SAE 0W-20',6,'flaconi',NULL,NULL),
  ('DR7-LUB-007','LUB','Bardahl 0W-20',2,'lattine',NULL,NULL),
  ('DR7-LUB-008','LUB','Bardahl 0W-30',2,'lattine',NULL,NULL),
  ('DR7-LUB-009','LUB','Bardahl 0W-40',3,'lattine',NULL,NULL),
  ('DR7-LUB-010','LUB','Bardahl 10W-40',2,'lattine',NULL,NULL),
  ('DR7-LUB-011','LUB','Bardahl 5W-40 (blu)',2,'lattine',NULL,NULL),
  ('DR7-LUB-012','LUB','Bardahl XTC 5W-40',1,'lattina',NULL,NULL),
  ('DR7-LUB-013','LUB','Bardahl 5W-30',1,'flacone',NULL,'Quasi terminato'),
  ('DR7-LUB-014','LUB','Mobil 1 0W-40',1,'flacone',NULL,NULL),
  ('DR7-LUB-015','LUB','Comaria ISO VG100',2,'flaconi',NULL,'1 nuovo + 1 quasi terminato'),
  ('DR7-LUB-016','LUB','Castrol GLS 75W-140',2,'flaconi',NULL,'1 nuovo + 1 a metà'),
  ('DR7-LUB-017','LUB','AdBlue',20,'2 taniche da 10 L',NULL,NULL),
  ('DR7-VER-001','VER','Pittura acrilica nera',3,'barattoli',NULL,NULL),
  ('DR7-VER-002','VER','Pittura spartitraffico acrilica',4,'barattoli',NULL,NULL),
  ('DR7-VER-003','VER','Smalto satinato ferro/legno',1,'barattolo',NULL,NULL),
  ('DR7-VER-004','VER','Smalto acriluretanico opaco',5,'barattoli',NULL,NULL),
  ('DR7-VER-005','VER','Stucco rasante murale',1,'barattolo',NULL,NULL),
  ('DR7-VER-006','VER','Tinta nera per asfalto',2,'barattoli',NULL,NULL),
  ('DR7-VER-007','VER','Diluente sintetico Haxton',10,'2 latte da 5 L',NULL,NULL),
  ('DR7-ABB-001','ABB','Cinture per pantalone',4,'pezzi',NULL,NULL),
  ('DR7-ABB-002','ABB','Pantaloncini corti da lavoro',3,'Taglia L',NULL,NULL),
  ('DR7-ABB-003','ABB','Pantaloncini corti da lavoro',4,'Taglia M',NULL,NULL),
  ('DR7-ABB-004','ABB','Scarpe donna con tacco',1,'Taglia 38',NULL,NULL),
  ('DR7-ABB-005','ABB','Pantaloncini corti da lavoro',2,'Taglia XL',NULL,NULL),
  ('DR7-ABB-006','ABB','Giacche nere da abito',2,'Taglia L ×1, M ×1',NULL,NULL),
  ('DR7-ABB-007','ABB','Borsello/Marsupio marchiato DR7',1,'pezzi',NULL,NULL),
  ('DR7-ABB-008','ABB','Pantaloni lunghi neri da lavoro',3,'Taglia M ×1, XL ×2',NULL,NULL),
  ('DR7-ABB-009','ABB','Pantalone lungo donna',1,'Taglia XS',NULL,NULL),
  ('DR7-ABB-010','ABB','Camicie bianche uomo',7,'Taglia S ×1, M ×5, XXL ×1',NULL,NULL),
  ('DR7-ABB-011','ABB','Mocassini uomo',2,'Taglia 42',NULL,NULL),
  ('DR7-ARR-001','ARR','Paletto dorato',1,'pezzi',NULL,NULL),
  ('DR7-ARR-002','ARR','Cordoni rossi',3,'pezzi',NULL,NULL),
  ('DR7-ARR-003','ARR','Cestini neri piccoli con apertura automatica',3,'pezzi',NULL,NULL),
  ('DR7-RIC-001','RIC','Tappetini in moquette Porsche Macan',4,'pezzi',NULL,NULL),
  ('DR7-RIC-002','RIC','Tastini alzacristalli Mercedes',1,'scatola',NULL,NULL),
  ('DR7-FRE-001','FRE','Pastiglie freno posteriori Mercedes GLE 63',1,'scatola',NULL,NULL),
  ('DR7-FRE-002','FRE','Pastiglie freno anteriori Mercedes GLE 63',1,'scatola',NULL,NULL),
  ('DR7-FRE-003','FRE','Pastiglie freno anteriori Porsche Cayenne S',2,'scatole',NULL,NULL),
  ('DR7-FRE-004','FRE','Pastiglie freno anteriori Smart',1,'scatola',NULL,NULL),
  ('DR7-FRE-005','FRE','Pastiglie freno anteriori Porsche 911 Carrera 4S',2,'scatole',NULL,NULL),
  ('DR7-FRE-006','FRE','Pastiglie freno anteriori Mercedes Vito',1,'scatola',NULL,NULL),
  ('DR7-FRE-007','FRE','Pastiglie freno posteriori BMW M2',1,'scatola',NULL,NULL),
  ('DR7-FRE-008','FRE','Pastiglie freno posteriori BMW M3',1,'scatola',NULL,NULL),
  ('DR7-FRE-009','FRE','Pastiglie freno anteriori Mercedes C63 AMG',1,'scatola',NULL,NULL),
  ('DR7-FRE-010','FRE','Pastiglie freno posteriori Mercedes C63 AMG',3,'scatole',NULL,NULL),
  ('DR7-FRE-011','FRE','Pastiglie freno posteriori Mercedes A45 S AMG',1,'scatola',NULL,NULL),
  ('DR7-FRE-012','FRE','Pastiglie freno anteriori Mercedes A45 S AMG',1,'scatola',NULL,NULL),
  ('DR7-FRE-013','FRE','Pastiglie freno anteriori Porsche Cayenne Coupé',1,'scatola',NULL,NULL),
  ('DR7-FRE-014','FRE','Pastiglie freno anteriori Porsche Macan GTS',1,'scatola',NULL,NULL),
  ('DR7-FRE-015','FRE','Pastiglie freno posteriori Porsche Macan GTS',2,'scatole',NULL,NULL),
  ('DR7-FRE-016','FRE','Pastiglie freno posteriori Mercedes Vito / V-Class',1,'scatola',NULL,NULL),
  ('DR7-FRE-017','FRE','Pastiglie freno anteriori Mercedes Classe B',1,'scatola',NULL,NULL),
  ('DR7-FRE-018','FRE','Pastiglie freno posteriori Mercedes Classe B',1,'scatola',NULL,NULL),
  ('DR7-FRE-019','FRE','Pastiglie freno anteriori Alfa Romeo MiTo',1,'scatola',NULL,NULL),
  ('DR7-FRE-020','FRE','Pastiglie freno anteriori Fiat 500',1,'scatola',NULL,NULL),
  ('DR7-FRE-021','FRE','Pastiglie freno posteriori BMW X5',1,'scatola',NULL,NULL),
  ('DR7-FRE-022','FRE','Pastiglie freno anteriori Jeep Renegade / Fiat 500X / Jeep Compass',1,'scatola',NULL,NULL),
  ('DR7-FRE-023','FRE','Pastiglie freno anteriori Audi A6 / VW Passat / Škoda Superb / Volvo',1,'scatola',NULL,NULL),
  ('DR7-LAV-001','LAV','Moquette',1,'bidone',70,NULL),
  ('DR7-LAV-002','LAV','Pulivetri',1,'bidone',90,NULL),
  ('DR7-LAV-003','LAV','Sponder',1,'bidone',80,NULL),
  ('DR7-LAV-004','LAV','Neon D3',1,'bidone',70,NULL),
  ('DR7-LAV-005','LAV','New Plastic',1,'latta',40,NULL),
  ('DR7-LAV-006','LAV','Prodotto per plastiche',1,'confezione',30,NULL),
  ('DR7-LAV-007','LAV','Shampoo',1,'bidone',40,NULL),
  ('DR7-LAV-008','LAV','Cera',1,'bidone',60,NULL),
  ('DR7-LAV-009','LAV','Nero gomme',1,'bidone',50,NULL),
  ('DR7-LAV-010','LAV','Flash',1,'bidone',80,NULL),
  ('DR7-LAV-011','LAV','Schiuma colorata',1,'bidone',50,NULL),
  ('DR7-LAV-012','LAV','Liquido refrigerante',1,'bidone',30,NULL),
  ('DR7-LAV-013','LAV','Ceramic Glaze (carrozzeria)',1,'confezione',40,NULL),
  ('DR7-BOM-001','BOM','Bomboletta di azoto',7,'pezzi',NULL,NULL),
  ('DR7-BOM-002','BOM','Sbloccante tipo CRC',10,'bombolette',NULL,NULL),
  ('DR7-BOM-003','BOM','Pulisci freni',6,'bombolette',NULL,NULL),
  ('DR7-BOM-004','BOM','Schiuma pulisci tessuti',2,'bombolette',NULL,NULL),
  ('DR7-BOM-005','BOM','Crema per pelle',2,'barattoli',NULL,'Formato 250 ml'),
  ('DR7-BOM-006','BOM','Deter Pelle (spruzzino)',6,'flaconi',NULL,'Formato 500 ml'),
  ('DR7-FIL-001','FIL','Filtro aria Audi RS3',1,'pezzi',NULL,NULL),
  ('DR7-FIL-002','FIL','Filtro carburante Mercedes Classe B',1,'pezzi',NULL,NULL),
  ('DR7-FIL-003','FIL','Filtro olio Fiat 500',1,'pezzi',NULL,NULL),
  ('DR7-FIL-004','FIL','Filtro olio Mercedes GLS63',1,'pezzi',NULL,NULL),
  ('DR7-FIL-005','FIL','Filtro olio OS682',1,'pezzi',NULL,NULL),
  ('DR7-FIL-006','FIL','Filtro aria K1246A',1,'pezzi',NULL,NULL),
  ('DR7-FIL-007','FIL','Filtro aria Mercedes-Benz FA0511JM',1,'pezzi',NULL,NULL),
  ('DR7-ELE-001','ELE','Multiprese elettriche',2,'pezzi',NULL,NULL),
  ('DR7-CAN-001','CAN','Nastro adesivo di carta (scotch carta)',4,'rotoli',NULL,'2 nuovi, 1 iniziato, 1 quasi terminato'),
  ('DR7-CAN-002','CAN','Nastro adesivo trasparente',1,'rotolo',50,NULL),
  ('DR7-CAN-003','CAN','Penne nere brandizzate DR7',0,'Esaurite - da riordinare',NULL,NULL),
  ('DR7-CAN-004','CAN','Batterie stilo AA',0,'Esaurite - da riordinare',NULL,NULL),
  ('DR7-CAN-005','CAN','Biglietti da visita DR7',0,'In attesa della nuova stampa',NULL,NULL),
  ('DR7-CAN-006','CAN','Cartucce colore per stampante',3,'pezzi',NULL,NULL),
  ('DR7-CAN-007','CAN','Toner per stampante',2,'pezzi',NULL,NULL),
  ('DR7-CAN-008','CAN','Angolari neri',9,'6 interi + 2 mezzi + 1 da 3/5',NULL,NULL),
  ('DR7-CAN-009','CAN','Post-it',6,'pacchi',NULL,NULL),
  ('DR7-CAN-010','CAN','Buste da lettera nere con sigillo dorato',2,'pacchi',NULL,NULL),
  ('DR7-CAN-011','CAN','Buste da lettera Total Black',1,'scatola',NULL,NULL),
  ('DR7-CAN-012','CAN','Tappetini per mouse marchiati DR7',2,'pezzi',NULL,NULL),
  ('DR7-CAN-013','CAN','Pennarelli blu per lavagna',6,'pezzi',NULL,NULL),
  ('DR7-CAN-014','CAN','Pennarelli rossi per lavagna',7,'pezzi',NULL,NULL)
ON CONFLICT (codice) DO UPDATE SET
  categoria_codice=EXCLUDED.categoria_codice, nome=EXCLUDED.nome,
  unita=EXCLUDED.unita, note=EXCLUDED.note;
